org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.20.6
minecraft_version_range=[1.20.6,1.21)
neo_version=20.6.88-beta
neo_version_range=[20.6,)
loader_version_range=[2,)

mod_id=endertrigon
mod_name=Ender Trigon
mod_license=All Rights Reserved
mod_version=1.20.6-1.0-beta
mod_group_id=nonamecrackers2.endertrigon
mod_authors=nonamecrackers2
mod_description=Mod that enhances the Ender Dragon fight\n\nFor SB737
crackerslib_version=1.20.6-0.1-beta
crackerslib_version_range=[1.20.6-0.0-pre,)